export const medicalDepartments = {
    "Cardiology": "Heart and blood vessels",
    "Neurology": "Brain and nervous system",
    "Orthopedics": "Bones, joints, and muscles",
    "Gastroenterology": "Digestive system",
    "Pulmonology": "Lungs and respiratory tract",
    "Nephrology": "Kidneys",
    "Endocrinology": "Hormones and glands",
    "Dermatology": "Skin",
    "Psychiatry": "Mental health",
    "Ophthalmology": "Eyes",
    "Otolaryngology": "Ear, nose, and throat (ENT)",
    "Rheumatology": "Joints and autoimmune diseases",
    "Urology": "Urinary tract and male reproductive organs",
    "Hematology": "Blood and blood-forming organs",
    "Oncology": "Cancer treatment",
    "Obstetrics and Gynecology": "Pregnancy and female reproductive system",
    "Pediatrics": "Children's health",
    "Geriatrics": "Elderly care",
    "General Surgery": "Surgical treatment of diseases",
    "Plastic Surgery": "Reconstructive and cosmetic surgery",
    "Emergency Medicine": "Acute and urgent care",
    "Family Medicine": "General healthcare across all ages",
    "Anesthesiology": "Pain relief and anesthesia",
    "Infectious Disease": "Contagious and infectious conditions",
    "Immunology": "Immune system disorders",
    "Pathology": "Disease diagnosis through lab analysis",
    "Radiology": "Imaging techniques (X-ray, MRI, etc.)",
    "Nuclear Medicine": "Radioactive substances in diagnosis/treatment",
    "Rehabilitation Medicine": "Restoration of physical function",
    "Occupational Medicine": "Health in the workplace",
    "Sports Medicine": "Injuries related to sports and exercise",
    "Pain Management": "Chronic pain treatment",
    "Palliative Care": "Serious illness symptom relief",
    "Allergy and Immunology": "Allergies and immune responses",
    "Dentistry": "Teeth and oral cavity",
    "Clinical Genetics": "Genetic disorders",
    "Forensic Medicine": "Medical application in law",
};
