const reasonOptions = {
    General: [
        "Fever and body aches",
        "Cold, cough, and sore throat",
        "Headache or migraine",
        "Fatigue or weakness",
        "General health check-up",
    ],
    Cardiologist: [
        "Chest pain or tightness",
        "Irregular heartbeat",
        "High blood pressure check-up",
        "Shortness of breath",
        "Palpitations",
    ],
    Cardiology: [
        "Chest pain or tightness",
        "Irregular heartbeat",
        "High blood pressure check-up",
        "Shortness of breath",
        "Palpitations",
    ],
    Neurology: [
        "Frequent headaches or migraines",
        "Dizziness or balance issues",
        "Numbness or tingling",
        "Memory loss",
        "Seizures or fainting spells",
    ],
    Orthopedics: [
        "Joint pain or swelling",
        "Back or neck pain",
        "Sports injury",
        "Difficulty walking or movement",
        "Post-fracture consultation",
    ],
    Ophthalmology: [
        "Blurred vision",
        "Eye redness or irritation",
        "Dry eyes or watering",
        "Vision check-up",
        "Eye pain or strain",
    ],
    ENT: [
        "Ear pain or hearing loss",
        "Sinus issues",
        "Throat pain or hoarseness",
        "Allergies or nasal congestion",
        "Tinnitus (ringing in ears)",
    ],
    Pediatrics: [
        "Fever or flu symptoms",
        "Vaccination",
        "Growth and development concerns",
        "Digestive issues",
        "Skin rashes or allergies",
    ],
    Gynecology: [
        "Irregular periods",
        "Pregnancy consultation",
        "Menstrual cramps or pain",
        "PCOD/PCOS concerns",
        "Vaginal discharge or infection",
    ],
    Dentistry: [
        "Toothache",
        "Bleeding gums",
        "Dental cleaning",
        "Cavity or filling",
        "Braces consultation",
    ],
    Dermatology: [
        "Skin rash or itching",
        "Acne or skin problems",
        "Sunburn or sun sensitivity",
        "Pimple or blemish",
        "Skin cancer check-up",
    ],
    Orthodontics: [
        "Braces",
        "Orthodontic treatment",
        "Orthodontic consultation",
        "Orthodontic treatment",
        "Orthodontic treatment",
    ],
    Immunology: [
        "Allergies",
        "Infections",
        "Vaccinations",
        "Immunization",
        "Immunization",
    ],
    Gastroenterology: [
        "Digestive issues",
        "Gastritis",
        "Ulcerative colitis",
        "Crohn's disease",
        "Irritable bowel syndrome",
    ],
    Pulmonology: [
        "Cough",
        "Shortness of breath",
        "Chest pain",
        "Pneumonia",
        "Asthma",
    ],
};

export default reasonOptions;
