const reasonOptions = {
    "Cardiology": [
        "Chest pain or tightness",
        "Irregular heartbeat",
        "High blood pressure check-up",
        "Shortness of breath",
        "Palpitations",
    ],
    "Neurology": [
        "Frequent headaches or migraines",
        "Dizziness or balance issues",
        "Numbness or tingling",
        "Memory loss",
        "Seizures or fainting spells",
    ],
    "Orthopedics": [
        "Joint pain or swelling",
        "Back or neck pain",
        "Sports injury",
        "Difficulty walking or movement",
        "Post-fracture consultation",
    ],
    "Gastroenterology": [
        "Digestive issues",
        "Gastritis",
        "Ulcerative colitis",
        "Crohn's disease",
        "Irritable bowel syndrome",
    ],
    "Pulmonology": [
        "Cough",
        "Shortness of breath",
        "Chest pain",
        "Pneumonia",
        "Asthma",
    ],
    "Nephrology": [
        "Chronic kidney disease",
        "Urinary issues",
        "Kidney stones",
        "Kidney failure check-up",
        "Blood in urine",
    ],
    "Endocrinology": [
        "Diabetes management",
        "Thyroid issues",
        "Hormonal imbalance",
        "Weight gain or loss",
        "Osteoporosis",
    ],
    "Dermatology": [
        "Skin rash or itching",
        "Acne or skin problems",
        "Sunburn or sun sensitivity",
        "Pimple or blemish",
        "Skin cancer check-up",
    ],
    "Psychiatry": [
        "Anxiety or depression",
        "Mood swings",
        "Stress management",
        "Sleep disorders",
        "Psychotic disorders",
    ],
    "Ophthalmology": [
        "Blurred vision",
        "Eye redness or irritation",
        "Dry eyes or watering",
        "Vision check-up",
        "Eye pain or strain",
    ],
    "Otolaryngology": [
        "Ear pain or hearing loss",
        "Sinus issues",
        "Throat pain or hoarseness",
        "Allergies or nasal congestion",
        "Tinnitus (ringing in ears)",
    ],
    "Rheumatology": [
        "Joint pain or stiffness",
        "Arthritis symptoms",
        "Autoimmune disease concerns",
        "Muscle pain or weakness",
        "Lupus or similar conditions",
    ],
    "Urology": [
        "Urinary tract infections",
        "Prostate concerns",
        "Kidney issues",
        "Bladder problems",
        "Sexual dysfunction",
    ],
    "Hematology": [
        "Anemia",
        "Blood clotting disorders",
        "Leukemia or blood cancer",
        "Iron deficiency",
        "Blood transfusion management",
    ],
    "Oncology": [
        "Cancer screening",
        "Tumor management",
        "Chemotherapy consultation",
        "Radiation therapy consultation",
        "Pain management for cancer",
    ],
    "Obstetrics and Gynecology": [
        "Irregular periods",
        "Pregnancy consultation",
        "Menstrual cramps or pain",
        "PCOD/PCOS concerns",
        "Vaginal discharge or infection",
    ],
    "Pediatrics": [
        "Fever or flu symptoms",
        "Vaccination",
        "Growth and development concerns",
        "Digestive issues",
        "Skin rashes or allergies",
    ],
    "Geriatrics": [
        "Mobility issues",
        "Memory problems",
        "Chronic disease management",
        "Dementia and Alzheimer’s care",
        "Elderly health screening",
    ],
    "General Surgery": [
        "Appendicitis",
        "Gallbladder surgery",
        "Hernia repair",
        "Bowel surgery",
        "Laparoscopic surgery",
    ],
    "Plastic Surgery": [
        "Cosmetic surgery",
        "Burn treatment",
        "Reconstructive surgery",
        "Skin grafts",
        "Scar treatment",
    ],
    "Emergency Medicine": [
        "Trauma care",
        "Acute illness",
        "Fracture management",
        "Injury from accidents",
        "Life-threatening conditions",
    ],
    "Family Medicine": [
        "General health check-up",
        "Chronic disease management",
        "Preventative care",
        "Vaccinations",
        "Annual physical exams",
    ],
    "Anesthesiology": [
        "Pre-surgical assessment",
        "Pain management",
        "Sedation during procedures",
        "General anesthesia",
        "Post-surgical pain control",
    ],
    "Infectious Disease": [
        "Infections",
        "Viral illnesses",
        "Fever and unknown causes",
        "Contagious diseases",
        "Immunization and vaccines",
    ],
    "Immunology": [
        "Allergies",
        "Infections",
        "Vaccinations",
        "Immunization",
        "Immunization",
    ],
    "Pathology": [
        "Blood tests",
        "Tissue biopsy",
        "Lab analysis of diseases",
        "Cancer screening",
        "Infectious disease testing",
    ],
    "Radiology": [
        "X-ray imaging",
        "MRI scans",
        "CT scans",
        "Ultrasound",
        "Radiation therapy planning",
    ],
    "Nuclear Medicine": [
        "Radioactive imaging",
        "Cancer detection",
        "Bone scans",
        "Thyroid treatment",
        "PET scan",
    ],
    "Rehabilitation Medicine": [
        "Physical therapy",
        "Post-surgery recovery",
        "Musculoskeletal rehabilitation",
        "Pain management",
        "Stroke recovery",
    ],
    "Occupational Medicine": [
        "Workplace injury care",
        "Work-related stress",
        "Occupational diseases",
        "Physical exams for workers",
        "Workplace safety consultations",
    ],
    "Sports Medicine": [
        "Sports injuries",
        "Strains and sprains",
        "Joint dislocations",
        "Rehabilitation after sports injuries",
        "Pre-participation physical exams",
    ],
    "Pain Management": [
        "Chronic pain management",
        "Back pain",
        "Joint pain",
        "Neuropathic pain",
        "Cancer-related pain",
    ],
    "Palliative Care": [
        "End-of-life care",
        "Pain and symptom management",
        "Comfort care",
        "Hospice care",
        "Chronic illness care",
    ],
    "Allergy and Immunology": [
        "Allergies",
        "Infections",
        "Vaccinations",
        "Immunization",
        "Immunization",
    ],
    "Dentistry": [
        "Toothache",
        "Bleeding gums",
        "Dental cleaning",
        "Cavity or filling",
        "Braces consultation",
    ],
    "Clinical Genetics": [
        "Genetic disorder screening",
        "Family history of genetic diseases",
        "Genetic counseling",
        "Inherited conditions",
        "DNA testing",
    ],
    "Forensic Medicine": [
        "Post-mortem analysis",
        "Medical-legal investigations",
        "Toxicology",
        "Accident or injury-related death",
        "Sexual assault examination",
    ],
};

export default reasonOptions;
